### ISSUE TITLE
Can't play video from path

### ISSUE THREAD

**Issue by ivan386** [bneijt/ipfs-video-frontend#1]
I try to play this video: [Первый день осени.mp4 (direct link)](https://gw.ipfs.video/ipfs/QmcYvAR934SzLuAxsL65wMAaWaxZ8NyC1bD2Sgy82mSWDU/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9%20%D0%B4%D0%B5%D0%BD%D1%8C%20%D0%BE%D1%81%D0%B5%D0%BD%D0%B8.mp4)
But player cant: [Первый день осени.mp4 (link to player)](https://ipfs.video/#/ipfs/QmcYvAR934SzLuAxsL65wMAaWaxZ8NyC1bD2Sgy82mSWDU/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9%20%D0%B4%D0%B5%D0%BD%D1%8C%20%D0%BE%D1%81%D0%B5%D0%BD%D0%B8.mp4)

**Comment by bneijt** [comment]
Yes, that is correct. Currently the player only supports direct content identifier links, not paths below a content identifier.

I'll mark this as a feature request. Thank you for opening this issue!

**Comment by bneijt** [comment]
The video will have to be recoded to WEBM,, VP8 and OPUS (see help on main page of ipfs.video) but will play through a gateway with the new version.

https://ipfs.video/gw/QmcYvAR934SzLuAxsL65wMAaWaxZ8NyC1bD2Sgy82mSWDU/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9%20%D0%B4%D0%B5%D0%BD%D1%8C%20%D0%BE%D1%81%D0%B5%D0%BD%D0%B8.mp4
