### ISSUE TITLE
Failed to use IPFS directly

### ISSUE THREAD

**Issue by veermetri05** [bneijt/ipfs-video-frontend#24]
Failed to use IPFS directly: Failed to append video buffer: 'QuotaExceededError: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.'

The video isn't even too large, it's about 50 MB this error occurs at around 50% of the video loaded.

**Comment by bneijt** [comment]
Which browser are you using and would it be possible for you to test this video in both Chrome and another browser? If the video is safe for work and legal to distribute, could you share the url?

**Comment by veermetri05** [comment]
This error also occurs on the BigBuckBunny example provided on the site. 
Load the page, wait till the video is loaded (wait till the whole video is loaded, if required watch the video). Nothing wrong happens for the first time with any video.
Reload the page, at this time the content of the video are cached, and the then we get the error.

I am using IPFS companion on Brave Browser and have a desktop client running. I have also tried this in Chrome (no IPFS companion plugin), the error still exists.

**Comment by bneijt** [comment]
IpfsVideo.vue:169 Failed to append video buffer. DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.
        at SourceBuffer.t (https://ipfs.video/index.bf569a9f.js:15:19834)
    t @ IpfsVideo.vue:169

https://developers.google.com/web/updates/2017/10/quotaexceedederror

Still no fix yet, but the article should help with finding one.
